### ISSUE TITLE
Background?

### ISSUE THREAD

**Issue by kbiesiadecki141** [kbiesiadecki141/cnuggs#3]
Someone needs to find a good background for the website besides the current boring white...

**Comment by karentheamerican** [comment]
I would say that our current background is a bit unsavory too, so I will be on the lookout for cool nugg-related backgrounds.

**Comment by kbiesiadecki141** [comment]
Similarly, your profile picture is unsavory.

**Comment by karentheamerican** [comment]
Understandable. But I have no regrets.

**Comment by kbiesiadecki141** [comment]
regerts*

**Comment by karentheamerican** [comment]
If you accept my pull request, the background is guaranteed to be savory.

**Comment by kbiesiadecki141** [comment]
It looks amazing. -Katelyn

eXceLLeNt wOrk -GeRT
