### ISSUE TITLE
Nav bar

### ISSUE THREAD

**Issue by kbiesiadecki141** [kbiesiadecki141/cnuggs#9]
At some point, we should try to move the code for the navbar into a separate html file so we can just link it in our other files (rather than having to retype it per file). Other solutions also welcome.

**Comment by karentheamerican** [comment]
Sounds sufficient. 

Unrelated to the navigation bar code, on "The Team" page the navigation bar no longer appears as one bar but splits into two separate bars. I don't know if it's just on Google Chrome, but if it isn't, I think it has something to do with the change in font for mine and Jenny's biographies. 

Also, for some reason "The Team" page is inaccessible from the "Random Nugg Generator"; clicking on "The Team" in the navigation bar yields no results.

**Comment by karentheamerican** [comment]
Scratch the previous claim; "The Team" page isn't accessible from the "Marry a Nugg" page, not the "Random Nugg Generator" page.

**Comment by kbiesiadecki141** [comment]
The most recent update resolves these issues.
